name: Compile and run unit tests
on: [push]


jobs:

  # Compile project
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install required packages
        run: sudo $GITHUB_WORKSPACE/.ci_scripts/compile-and-test/install_packages.sh

      - name: Build project
        run: $GITHUB_WORKSPACE/.ci_scripts/compile-and-test/build_project.sh

      - name: Run CUnit tests
        run: $GITHUB_WORKSPACE/.ci_scripts/compile-and-test/run_tests.sh
